blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/CraftCanvasMC/Canvas/discussions/new?category=feature-requests
    about: Suggest an idea for Canvas
  - name: Exploit Report
    url: https://discord.com/invite/hs7EYwWf4G
    about: |
      Since GitHub does not allow private issues, exploit reports are currently handled through our Discord.
      To report an exploit, contact a moderator on the Canvas Discord.
  - name: PCanvas Discord
    url: https://discord.com/invite/hs7EYwWf4G
    about: If you are having issues with Spark profiling or have other minor issues, come join our Discord server for help!
